### PR TITLE
Designed Login page

### PR DESCRIPTION
**Pull request by simranquirky**
Sign In and Sign Up page.

Looks like:

Screenshot (418)

The devincept logo can be replaced by DevMerch logo

On clicking "already a member the box reverts to the sign in page.

This PR attempts to close issue #6

### CODE REVIEW

**Comment by foreverabhi2002** [comment]
@simranquirky make some changes:-

- For the logo instead of using background property use img property, because it might conflict when we add another background to the website.
- In responsive or mobile version, the logo gets to the bottom of the form which looks okay, but when we scale down the web view to 0.5x, the logo doesn't fit under the form and so logo can be seen a bit for that make sure of using visibility hidden property.
- Currently we are starting with the front-end only so there's no need of separate front-end folder, instead just push the index file on the root folder and css file inside the css folder inside the root.

**Comment by simranquirky** [comment]
Ok , I will implement these changes.

**Comment by simranquirky** [comment]
The requested changes has been made @foreverabhi2002

**Comment by foreverabhi2002** [comment]
@simranquirky make the above changes as shown in the index.html file.
DevMerch (2)_LI
Screenshot (38)

- Close the img tag on line 72.
- use *< link rel="stylesheet" type="text/css" href="css/index.css">* property instead of  *<style src="css/index.css"></style>* property on line 75.
- Add the above link property inside head tag and under the title tag.
- For the mobile version, keep the logo above the form and not in the bottom.
- The thing I mentioned before that files should be inside root folder it didn't mean literally "root folder", root folder meant where the other files are kept like Licence and Readme file because previously you made a Folder name frontend which it doesn't require. So do not make any folder and keep the index.html file next to the readme file. For css its correct should be inside css folder only.

Apology for not clearing it properly before, you can reach out to me on Slack for better clarifications.

**Comment by simranquirky** [comment]
Ok 😅

**Comment by simranquirky** [comment]
Screenshot (425)

WhatsApp Image 2021-08-02 at 11 15 25 AM

**Comment by foreverabhi2002** [comment]
Congrats @simranquirky 
Your pull request has been merged.

**Pull request merged**
